apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  DB_NAME: mydatabase
  DB_USER: postgres
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
